[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
capstone = "3ECCL8btDKSnNYEgu15UZca4epL2PdHqDEYdY9UBvmcP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
